server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: ${MYSQL_PWD:123456}
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: org.example.user.entity

logging:
  level:
    org.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS