server:
  port: 8088

spring:
  application:
    name: order-service
  profiles:
    active:
      dev
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: ${MYSQL_PWD:123456}
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  type-aliases-package: org.example.demo.order.entity

logging:
  level:
    org.example: debug

